/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_housing_project;

import static e_housing_project.MDIframe.jMenuItem5;
import static e_housing_project.MDIframe.jMenuItem6;
import static e_housing_project.owner_page.jTable1;
import static e_housing_project.starting_frame.owner_id;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Indrajeet singh
 */
public class search_pro extends javax.swing.JInternalFrame {

    /**
     * Creates new form search_pro
     */
    public search_pro() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);
        Dimension dmnsn = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dmnsn);
        property_search_filter();
        jMenuItem6.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Type");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel11.setText("Floor");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel12.setText("Budget");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        jLabel13.setText("Balcony");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel14.setText("Facing");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel15.setText("Furnishing");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel16.setText("Covered Area");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 79, -1));

        jLabel17.setText("Preferred");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel18.setText("Amenties");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel19.setText("Posted Since");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 430, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 223, 450, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 450, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 450, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 326, 450, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 450, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 463, 450, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 450, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 103, 450, 10));

        jRadioButton1.setText("1BHK");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 7, -1, -1));

        jRadioButton2.setText("2BHK");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jRadioButton3.setText("3BHK");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jRadioButton4.setText("5BHK");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jRadioButton5.setText("4BHK");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jRadioButton6.setText("Ground");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 62, -1, -1));

        jRadioButton7.setText("Basement");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 62, -1, -1));

        jRadioButton8.setText("1st");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 62, -1, -1));

        jRadioButton9.setText("2nd");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 62, -1, -1));

        jRadioButton10.setText("3rd");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 62, -1, -1));

        jRadioButton11.setText("4th");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 62, -1, -1));

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setText("1k - 2k");
        jPanel2.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        buttonGroup3.add(jRadioButton13);
        jRadioButton13.setText("2k - 3k");
        jPanel2.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        buttonGroup3.add(jRadioButton14);
        jRadioButton14.setText("10k +");
        jPanel2.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        buttonGroup3.add(jRadioButton15);
        jRadioButton15.setText("5k - 10k");
        jPanel2.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        buttonGroup3.add(jRadioButton16);
        jRadioButton16.setText("3k - 4k");
        jPanel2.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        buttonGroup3.add(jRadioButton17);
        jRadioButton17.setText("4k - 5k");
        jPanel2.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        buttonGroup4.add(jRadioButton18);
        jRadioButton18.setText("North-west");
        jPanel2.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        buttonGroup4.add(jRadioButton19);
        jRadioButton19.setText("North");
        jPanel2.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        buttonGroup4.add(jRadioButton20);
        jRadioButton20.setText("East");
        jPanel2.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        buttonGroup4.add(jRadioButton21);
        jRadioButton21.setText("South");
        jPanel2.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        buttonGroup4.add(jRadioButton22);
        jRadioButton22.setText("West");
        jPanel2.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        buttonGroup4.add(jRadioButton23);
        jRadioButton23.setText("North-East");
        jPanel2.add(jRadioButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        buttonGroup4.add(jRadioButton24);
        jRadioButton24.setText("South-East");
        jPanel2.add(jRadioButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        buttonGroup4.add(jRadioButton25);
        jRadioButton25.setText("South-west");
        jPanel2.add(jRadioButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        buttonGroup5.add(jRadioButton26);
        jRadioButton26.setText("Unfurnished");
        jPanel2.add(jRadioButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        buttonGroup5.add(jRadioButton27);
        jRadioButton27.setText("Semi-furnished");
        jPanel2.add(jRadioButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        buttonGroup5.add(jRadioButton28);
        jRadioButton28.setText("Furnished");
        jPanel2.add(jRadioButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        buttonGroup7.add(jRadioButton29);
        jRadioButton29.setText("Yes");
        jPanel2.add(jRadioButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        buttonGroup6.add(jRadioButton30);
        jRadioButton30.setText("Both");
        jPanel2.add(jRadioButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        buttonGroup6.add(jRadioButton31);
        jRadioButton31.setText("Bachlors");
        jPanel2.add(jRadioButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        buttonGroup6.add(jRadioButton32);
        jRadioButton32.setText("family");
        jPanel2.add(jRadioButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        buttonGroup7.add(jRadioButton33);
        jRadioButton33.setText("No");
        jPanel2.add(jRadioButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jCheckBox1.setText("Lift");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jCheckBox2.setText("Garden");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        jCheckBox3.setText("Parking");
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jCheckBox4.setText("Air-conditioned");
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jCheckBox5.setText("Water tank");
        jPanel2.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jCheckBox6.setText("Wi-fi");
        jPanel2.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jRadioButton34.setText("Last month");
        jPanel2.add(jRadioButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        jRadioButton35.setText("Last week");
        jPanel2.add(jRadioButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        jRadioButton36.setText("Last 3 week");
        jPanel2.add(jRadioButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        jRadioButton37.setText("Last 2 week");
        jPanel2.add(jRadioButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jRadioButton38.setText("All");
        jPanel2.add(jRadioButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jRadioButton39.setText("150+ sqft. ");
        jPanel2.add(jRadioButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jRadioButton40.setText("0-25 sqft.");
        jPanel2.add(jRadioButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jRadioButton41.setText("25-50 sqft.");
        jRadioButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton41ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jRadioButton42.setText("75-100 sqft.");
        jPanel2.add(jRadioButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jRadioButton43.setText("100-150 sqft");
        jPanel2.add(jRadioButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jRadioButton44.setText("50-75 sqft.");
        jPanel2.add(jRadioButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 710));

        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 710, 390));

        jLabel1.setText("Total search result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jLabel2.setText("0");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 230, 10));

        jButton1.setText("View details");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 300, 60));

        jButton2.setText("Book");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 360, 60));

        jLabel3.setText("City");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 50, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 160, -1));

        jLabel4.setText("Colony");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 160, -1));

        jLabel5.setText("Location");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 210, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 62, 230, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 122, 230, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton41ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        property_search_filter();// TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         property_search_filter();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:\
        property_search_filter();
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        property_search_filter();
    }//GEN-LAST:event_jRadioButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void property_search_filter() {
        //To change body of generated methods, choose Tools | Templates.
        String filter="select owner_id,rent,city,colony from property_master where";
        try
        {
            
 //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>        
          if(jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected() || jRadioButton4.isSelected() || jRadioButton5.isSelected())
          {
//             filter= filter.concat(" type =");
          if(jRadioButton1.isSelected())
               filter = filter.concat(" type ='1BHK' or");
          if(jRadioButton2.isSelected())
               filter = filter.concat(" type ='2BHK' or");  
          if(jRadioButton3.isSelected())
               filter = filter.concat(" type ='3BHK' or"); 
           if(jRadioButton5.isSelected())
               filter = filter.concat(" type ='4BHK' or"); 
            if(jRadioButton4.isSelected())
               filter = filter.concat(" type ='5BHK' or"); 
            
          if(filter.endsWith("or"))
                  {
                      int index = filter.lastIndexOf("or");
                      filter = filter.substring(0, index);
                      filter=filter.concat(" and");
                  }
          }
            
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

 if(jRadioButton6.isSelected() || jRadioButton7.isSelected() || jRadioButton8.isSelected() || jRadioButton9.isSelected() || jRadioButton10.isSelected() || jRadioButton11.isSelected())
          {
//             filter= filter.concat(" type =");
          if(jRadioButton6.isSelected())
               filter = filter.concat(" floor = 0 or");
          if(jRadioButton7.isSelected())
               filter = filter.concat(" floor = 1 or");  
          if(jRadioButton8.isSelected())
               filter = filter.concat(" floor = 2 or"); 
           if(jRadioButton9.isSelected())
               filter = filter.concat(" floor = 3 or"); 
            if(jRadioButton10.isSelected())
               filter = filter.concat(" floor = 4 or"); 
            if(jRadioButton11.isSelected())
               filter = filter.concat(" floor = 5 or");
            
          if(filter.endsWith("or"))
                  {
                      int index = filter.lastIndexOf("or");
                      filter = filter.substring(0, index);
                      filter=filter.concat(" and");
                  }
          }
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            if(jRadioButton12.isSelected())
               filter = filter.concat(" rent>= 1000 and rent <=2000 and");
            if(jRadioButton13.isSelected())
               filter = filter.concat(" floor = 1 and");  
            if(jRadioButton16.isSelected())
               filter = filter.concat(" floor = 2 and"); 
            if(jRadioButton17.isSelected())
               filter = filter.concat(" floor = 3 and"); 
            if(jRadioButton14.isSelected())
               filter = filter.concat(" floor = 4 and");
            if(jRadioButton15.isSelected())
               filter = filter.concat(" floor = 5 and"); 
//           
            
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<          
            
            
          if(filter.endsWith("where"))
                  {
                      int index = filter.lastIndexOf("where");
                      filter = filter.substring(0, index);
                  }
         if(filter.endsWith("and"))
         {
          int index = filter.lastIndexOf("and");
          filter = filter.substring(0, index);
         }
          System.out.println(filter);
          DriverManager.registerDriver(new oracle.jdbc.OracleDriver()); 
          Connection c;
          c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678"); Statement stmt = c.createStatement();
          ResultSet rs;
          rs = stmt.executeQuery(filter);
          jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           int count = jTable1.getRowCount();
           jLabel2.setText((count+""));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error"+e);
        }
    }
}
