package e_housing_project;

import static e_housing_project.MDIframe.dp1;
import static e_housing_project.owner_page.id;
import static e_housing_project.starting_frame.owner_id;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import static oracle.net.aso.C11.i;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Indrajeet singh
 */
public class update_property extends javax.swing.JInternalFrame {
Object pid;
    /**
     * Creates new form update_property
     * @param pid
     */
    public update_property(Object pid) {
        initComponents();
        this.pid=pid;

          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);
        Dimension dmnsn = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dmnsn);
        load();
        set_property(this.pid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Electricity bill");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Amenties");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Type");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Floor");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Facing");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Water bill");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Furnishing");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Balcony");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Yes");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");

        jCheckBox1.setText("Lift");

        jCheckBox2.setText("Garden");

        jCheckBox3.setText("Parking");

        jCheckBox5.setText("Water tank");

        jCheckBox6.setText("Wi-fi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1BHK", "2BHK", "3BHK", "4BHK", "5BHK" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North", "South", "East", "West" }));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Furnished", "Semi-furnished", "Unfurnished" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combine in rent", "Separate" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ground", "Basement", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combine in rent", "Separate" }));

        jCheckBox4.setText("Air-conditioned");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("No");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Yes");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Available for public");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Prefrred");

        jCheckBox7.setText("Family");

        jCheckBox8.setText("Bachlor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(192, 192, 192))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox7)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4)
                                .addGap(33, 33, 33)
                                .addComponent(jRadioButton3)))
                        .addGap(105, 105, 105)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox1)
                        .addComponent(jCheckBox2)
                        .addComponent(jCheckBox3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox4))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox7)
                        .addComponent(jCheckBox8)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton3)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 410, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Area of property");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Location");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pincode");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Rent ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Landmark");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Colony");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, -1));

        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 280, -1));

        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, -1));

        jTextField5.setBorder(null);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 280, -1));

        jTextField6.setBorder(null);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 280, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 280, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 280, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 280, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 280, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 280, -1));

        jComboBox6.setBorder(null);
        jComboBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox6ItemStateChanged(evt);
            }
        });
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 260, 20));

        jPanel1.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("City");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagess/icons8-back-arrow-24.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("property Id ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 360, 500));

        jButton1.setText("Update Propety");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1080, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Images"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 310, 430));

        jButton2.setText("Browse Images");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 23, 310, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type = jComboBox1.getSelectedItem().toString();
        int locality_id=jComboBox8.getSelectedIndex();
        int rent =Integer.parseInt(jTextField2.getText());
        System.out.print(rent);
//        String posted_date =jTextField4.getText().toString();
        int area = Integer.parseInt(jTextField1.getText());
        System.out.print(area);
        int floor;
        floor = jComboBox2.getSelectedIndex();
        System.out.print(floor);
         String city =jComboBox6.getSelectedItem().toString();
        System.out.print(city);
         String location =jComboBox8.getSelectedItem().toString();
        System.out.print(location);
        try{
             DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
           System.out.println("3"); 
          Connection c4;
           Statement stmt4;
            c4 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
           System.out.println("4");
            stmt4=c4.createStatement();
             System.out.println("5");
             ResultSet rs4;
            rs4 = stmt4.executeQuery("select locality_id from locality_master where city='"+city+"' and location_name='"+location+"'");
            rs4.next();
      locality_id = rs4.getInt("locality_id");  
      c4.close();
        }
        catch(SQLException e)
        {
            
        }
       
//        System.out.print(locality_id);
        String water= jComboBox7.getSelectedItem().toString();
        System.out.print(water);
        String electricity = jComboBox5.getSelectedItem().toString();
        System.out.print(electricity);
        String facing= jComboBox3.getSelectedItem().toString();
        System.out.print(facing);
        String preferred="";
          if(jCheckBox7.isSelected())
            preferred+="Family";
        if(jCheckBox8.isSelected())
            preferred+="Bachlor";
        
        System.out.print(preferred);
        
        String furnishing= jComboBox4.getSelectedItem().toString();
        System.out.print(furnishing);
        
        String amenties="";
        if(jCheckBox1.isSelected())
            amenties+=" Lift ";
        if(jCheckBox2.isSelected())
            amenties+=" Garden ";
        if(jCheckBox3.isSelected())
            amenties+=" Parking ";
        if(jCheckBox4.isSelected())
            amenties+=" Air-conditioned ";
        if(jCheckBox5.isSelected())
            amenties+=" Water-tank ";
        if(jCheckBox6.isSelected())
            amenties+=" Wi-fi ";
      System.out.print(amenties);
            
        String balcony="";
        if(jRadioButton1.isSelected())
            balcony+="Yes";
        else
            balcony+="No";
 
        System.out.print(balcony);
         String available="";
        if(jRadioButton1.isSelected())
            available+="yes";
        else
            available+="Not";
      
        System.out.print(available);
        int id=owner_id;
       
       
        String pincode =jTextField4.getText();
        System.out.print(pincode);
        String landmark =jTextField5.getText();
        System.out.print(landmark);
        String colony =jTextField6.getText();
        System.out.print(colony);
        
        String sql ="update property_master set type ='"+type+"', rent = "+rent+",area = "+area+", floor ="+floor+", water = '"+water+"', electricity ='"+electricity+"',facing = '"+facing+"', preferred = '"+preferred+"', furshing = '"+furnishing+"',amenties = '"+amenties+"',balcony = '"+balcony+"',available = '"+available+"',city = '"+city+"', pincode = '"+pincode+"',landmark = '"+landmark+"',colony =  '"+colony+"',locality_id = "+locality_id+" where property_id = "+pid ;
       
        Statement stmt;
        try{
        System.out.println("2");
          DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
           System.out.println("3"); 
          Connection c;
            c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
           System.out.println("4");
            stmt=c.createStatement();
             System.out.println("5");
             stmt.executeUpdate(sql);            
            c.close();
           JOptionPane.showMessageDialog(null,"Successfully updated the property : \n property id is "+pid+" ");
           
           owner_page op=new owner_page();
           dp1.add(op);
           
           op.setVisible(true);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error"+e);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
//        jComboBox8.removeAllItems();
//        String ct=jComboBox6.getSelectedItem().toString();
//        try{
//
//            ResultSet rs2;
//            Statement stmt2;
//            Connection c2;
//            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
//
//            c2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
//            stmt2=c2.createStatement();
//            rs2= stmt2.executeQuery("select location_name from locality_master where city = '"+ct+"'");
//            while(rs2.next())
//            {
//                String l = rs2.getString("location_name");
//                jComboBox8.addItem(l);
//            }
//            c2.close();
//        }
//        catch(SQLException e){
//            JOptionPane.showMessageDialog(null,"Error"+e);
//        }

    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg");
        jFileChooser1.addChoosableFileFilter(filter);
        int result = jFileChooser1.showDialog(this, title);
        if(result == JFileChooser.APPROVE_OPTION){
            File sf = jFileChooser1.getSelectedFile();
            String path = sf.getAbsolutePath();
           
        }
//        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
       owner_page op=new owner_page();
           dp1.add(op);
           
           op.setVisible(true);
           id=-1;
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jComboBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox6ItemStateChanged
        // TODO add your handling code here:
//          jComboBox8.removeAllItems();
//        String ct=jComboBox6.getSelectedItem().toString();
//        try{
//
//            ResultSet rs2;
//            Statement stmt2;
//            Connection c2;
//            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
//
//            c2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
//            stmt2=c2.createStatement();
//            rs2= stmt2.executeQuery("select location_name from locality_master where city = '"+ct+"'");
//            while(rs2.next())
//            {
//                String l = rs2.getString("location_name");
//                jComboBox8.addItem(l);
//            }
//            c2.close();
//        }
//        catch(SQLException e){
//            JOptionPane.showMessageDialog(null,"Error"+e);
//        }
    }//GEN-LAST:event_jComboBox6ItemStateChanged

    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked
        // TODO add your handling code here:
//          jComboBox8.removeAllItems();
//        String ct=jComboBox6.getSelectedItem().toString();
//        try{
//
//            ResultSet rs2;
//            Statement stmt2;
//            Connection c2;
//            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
//
//            c2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
//            stmt2=c2.createStatement();
//            rs2= stmt2.executeQuery("select location_name from locality_master where city = '"+ct+"'");
//            while(rs2.next())
//            {
//                String l = rs2.getString("location_name");
//                jComboBox8.addItem(l);
//            }
//            c2.close();
//        }
//        catch(SQLException e){
//            JOptionPane.showMessageDialog(null,"Error"+e);
//        }
    }//GEN-LAST:event_jComboBox6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void set_property(Object id1) {
       try{
           
           jLabel20.setText(id+"");
           System.out.print("HI");
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver()); 
          Connection c;
          c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678"); 
          
          Statement stmt1,stmt = c.createStatement();
          ResultSet rs,rs1;
          stmt1 =c.createStatement();
         
          System.out.print("HI"+id1);
          
          rs = stmt.executeQuery("select  * from  property_master where property_id="+id1);
         
          rs.next();
          String area =rs.getString("area");
          System.out.print("hello"+area);
          jTextField1.setText(area);
          int locality_id=rs.getInt("locality_id");
         
          rs1 =  stmt1.executeQuery("select location_name from locality_master where locality_id="+locality_id);
          rs1.next();
          String location_name;
//          location_name = rs1.getString("location_name");
//           System.out.println("hello"+location_name);
        
         ComboBoxModel<String> mm1 = jComboBox8.getModel();
          mm1.setSelectedItem(rs1.getString("location_name"));
          
           
          String rent = rs.getString("rent");
          System.out.print("hello"+rent);
          jTextField2.setText(rent);
          
          String city = rs.getString("city");
          System.out.print("hello"+city);
           ComboBoxModel<String> mm2 = jComboBox6.getModel();
          mm2.setSelectedItem(city);
          
          String pincode = rs.getString("pincode");
          System.out.print("hello"+pincode);
          jTextField4.setText(pincode);
          
          String landmark = rs.getString("landmark");
          System.out.print("hello"+landmark);
          jTextField5.setText(landmark);
          
          String colony = rs.getString("colony");
          System.out.print("hello"+colony);
          jTextField6.setText(colony);
          
          String type = rs.getString("type");
          System.out.print("hello"+type);
           ComboBoxModel<String> m = jComboBox1.getModel();
          m.setSelectedItem(type);
          
          int floor = rs.getInt("floor");
          System.out.print("hello"+floor);
            jComboBox2.setSelectedIndex(floor);
           
           
          
          String facing = rs.getString("facing");
          System.out.print("hello"+facing);
          ComboBoxModel<String> m1 = jComboBox3.getModel();
          m1.setSelectedItem(facing);
          
          String furnishing = rs.getString("furshing");
          System.out.print("hello"+furnishing);
          ComboBoxModel<String> m2 = jComboBox4.getModel();
          m2.setSelectedItem(furnishing);
          
          
          String water = rs.getString("water");
          System.out.print("hello"+water);
          ComboBoxModel<String> m3 = jComboBox7.getModel();
          m3.setSelectedItem(water);
          
         
          String electricity = rs.getString("electricity");
          System.out.print("hello"+electricity);
          ComboBoxModel<String> m4 = jComboBox5.getModel();
          m4.setSelectedItem(electricity);
          
          
          String balcony = rs.getString("balcony");
          System.out.print("hello"+balcony);
           if(balcony.equals("Yes"))
              jRadioButton1.setSelected(true);
          else
              jRadioButton2.setSelected(true);
           
           
          String amenties = rs.getString("amenties");
          System.out.print("hello"+amenties);
          if(amenties.contains("Lift"))
              jCheckBox1.setSelected(true);
           if(amenties.contains("Garden"))
              jCheckBox2.setSelected(true);
            if(amenties.contains("Parking"))
              jCheckBox3.setSelected(true);
             if(amenties.contains("Wi-fi"))
              jCheckBox6.setSelected(true);
              if(amenties.contains("Water"))
              jCheckBox5.setSelected(true);
               if(amenties.contains("Air-conditioned"))
              jCheckBox4.setSelected(true);
          
          String preferred = rs.getString("preferred");
          System.out.print("hello"+preferred);
           if(preferred.contains("Family"))
              jCheckBox7.setSelected(true);
            if(preferred.contains("Bachlor"))
              jCheckBox8.setSelected(true);
          
          String available = rs.getString("available");
          System.out.print("hello"+available);
           if(balcony.equals("Yes"))
              jRadioButton4.setSelected(true);
          else
              jRadioButton3.setSelected(true);
          
          
       }
       catch(SQLException e)
       {
           
       }
    }

    private void load() {
        try{
              ResultSet rs,rs1;
              Statement stmt1,stmt2;
              Connection c1;
              DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
           
            c1 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","12345678");
             stmt1=c1.createStatement();
                    stmt2=c1.createStatement();
            rs= stmt1.executeQuery("select distinct city from locality_master ");
            rs1= stmt2.executeQuery("select distinct location_name from locality_master ");
           
                while(rs.next())
                {
                String ct = rs.getString("city");
              
                jComboBox6.addItem(ct);
               
                }
                
                while(rs1.next())
                {
              
                String ln= rs1.getString("location_name");
                jComboBox8.addItem(ln);
                }
               
         }
         catch(SQLException e)
         {
             JOptionPane.showMessageDialog(null,"Error"+e);
         }
    }

    private Icon ResizeImage(String path) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
